# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        args:
          - --branch=develop

  - repo: https://github.com/s3rius/pre_commit_hooks
    rev: 0.3.1
    hooks:
      - id: linked_todos
        args:
          - FIXME
      - id: commit_msg_prefix
        args:
          - '-f={} '

  - repo: local
    hooks:

      - id: isort
        name: isort
        entry: isort
        language: system
        exclude: migrations
        types: [ python ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-duplicate-keys ]

      - id: yesqa
        name: yesqa
        entry: yesqa
        language: system
        always_run: true
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args:
          - --count

      - id: mypy
        name: mypy
        entry: "./run-mypy.sh"
        language: system
        require_serial: true
        types: [ python ]
